name: never_forget
description: A simple yet powerfull reminder app

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  intl: ^0.15.8
  hive: ^1.1.1
  hive_flutter: ^0.2.1
  flutter_local_notifications: ^0.8.4+3
  rxdart: ^0.22.6
  bloc_provider: ^0.6.2+2
  shared_preferences: ^0.5.4+8
  find_dropdown: ^0.1.7+1

  # Util
  path_provider: ^1.3.0
  image_picker: ^0.6.2+1
  numberpicker: ^1.1.0
  day_selector: ^1.0.0

  # UI
  cupertino_icons: ^0.1.2
  table_calendar: ^2.2.1
  settings_ui: ^0.2.0
  fluttertoast: ^3.1.3
  flutter_icons: ^1.0.0+1
  flutter_datetime_picker: ^1.2.8
  bottom_navy_bar: ^5.2.2
  gg_flutter_components:
    git:
      url: git://github.com/rodrigobastosv/gg_flutter_components.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.2
  build_runner: ^1.7.1

dependency_overrides:
  intl: ^0.15.8

flutter:
  uses-material-design: true